name: TheLifeOfAron
favicon: null
layout_spectrum: 0.64979
typography_spectrum: 0.05579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffb'
    - '#bcbbb6'
    - '#7b797a'
    - '#222126'
    - '#f28684'
  brandStrength: 0.5
  lightness: 0.7677791707683355
  saturation: 0.3125
  rhythmicContrast: 0.9811049401760101
purpose: []
